import type { Lot, AuctionWeekEvent, PlatformStats } from '@/src/types/auction';

export const NEXT_AUCTION: AuctionWeekEvent = {
  date:         '2026-03-20T15:00:00+04:00',
  lotCount:     14,
  location:     'Dubai Warehouse · Al Quoz Industrial Area',
  viewingStart: '2026-03-18T10:00:00+04:00',
  viewingEnd:   '2026-03-19T17:00:00+04:00',
};

export const PLATFORM_STATS: PlatformStats = {
  lotsSold:       2400,
  transactedAed:  1_200_000_000,
  verifiedBuyers: 850,
  maxDiscountPct: 50,
};

export const FEATURED_LOTS: Lot[] = [
  {
    id:            'lot-001',
    lotNumber:     'DXB-1024',
    title:         'Hyundai Elantra N-Line',
    make:          'Hyundai',
    model:         'Elantra N-Line',
    year:          2022,
    mileageKm:     46_210,
    condition:     'Excellent',
    fuelType:      'Petrol',
    bodyType:      'Sedan',
    regionSpec:    'GCC',
    color:         'White',
    emirate:       'Dubai',
    category:      'sedan',
    status:        'LIVE',
    currentBidAed: 48_000,
    startingBidAed:38_000,
    marketPriceAed:77_000,
    minStepAed:    1_000,
    startsAt:      '2026-03-20T14:00:00+04:00',
    endsAt:        '2026-03-20T16:00:00+04:00',
    imageUrl:      '/images/car-elantra.jpg',
    totalBids:     12,
  },
  {
    id:            'lot-002',
    lotNumber:     'DXB-5112',
    title:         'Mercedes-AMG G 63',
    make:          'Mercedes-Benz',
    model:         'AMG G 63',
    year:          2021,
    mileageKm:     62_000,
    condition:     'Good',
    fuelType:      'Petrol',
    bodyType:      'SUV',
    regionSpec:    'GCC',
    color:         'Black',
    emirate:       'Dubai',
    category:      'suv',
    status:        'SCHEDULED',
    currentBidAed: 295_000,
    startingBidAed:295_000,
    marketPriceAed:405_000,
    minStepAed:    2_000,
    startsAt:      '2026-03-20T15:00:00+04:00',
    endsAt:        '2026-03-20T17:00:00+04:00',
    imageUrl:      '/images/car-gwagon.jpg',
    totalBids:     0,
  },
  {
    id:            'lot-003',
    lotNumber:     'AUH-2088',
    title:         'Bentley Continental GTC',
    make:          'Bentley',
    model:         'Continental GTC',
    year:          2020,
    mileageKm:     84_500,
    condition:     'Good',
    fuelType:      'Petrol',
    bodyType:      'Coupe',
    regionSpec:    'GCC',
    color:         'Silver',
    emirate:       'Abu Dhabi',
    category:      'luxury',
    status:        'SCHEDULED',
    currentBidAed: 390_000,
    startingBidAed:390_000,
    marketPriceAed:695_000,
    minStepAed:    5_000,
    startsAt:      '2026-03-20T15:00:00+04:00',
    endsAt:        '2026-03-20T17:30:00+04:00',
    imageUrl:      '/images/car-bentley.jpg',
    totalBids:     0,
  },
];

export const CATEGORIES = [
  { slug: 'luxury', label: 'Luxury Fleet',      sub: 'Bentley, Rolls-Royce, Maserati', image: '/images/car-bentley.jpg' },
  { slug: 'suv',    label: 'SUVs',               sub: 'G-Wagon, Land Cruiser, Patrol',  image: '/images/car-gwagon.jpg'  },
  { slug: 'sedan',  label: 'Fleet Sedans',        sub: 'Elantra, Camry, Accord',         image: '/images/car-elantra.jpg' },
  { slug: 'sports', label: 'Sports & Supercars',  sub: 'McLaren, Mustang, Ferrari',       image: '/images/car-mclaren.jpg' },
];
