ALTER TYPE "UserStatus" ADD VALUE IF NOT EXISTS 'PENDING_APPROVAL';
ALTER TYPE "CompanyStatus" ADD VALUE IF NOT EXISTS 'PENDING_APPROVAL';
ALTER TYPE "CompanyUserRole" ADD VALUE IF NOT EXISTS 'SELLER_MANAGER';
ALTER TYPE "CompanyUserRole" ADD VALUE IF NOT EXISTS 'BUYER_BIDDER';

ALTER TABLE "User"
  ALTER COLUMN "passwordHash" DROP NOT NULL;
