var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/my-bids/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__9fa22c69._.js")
R.c("server/chunks/ssr/_566c6625._.js")
R.c("server/chunks/ssr/_e3809476._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5155cd89._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7f68cf2f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__f5a4994d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_my-bids_page_actions_bbc98451.js")
R.m(56914)
module.exports=R.m(56914).exports
