ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "fuelType" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "transmission" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "bodyType" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "regionSpec" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "condition" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "serviceHistory" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "sellerNotes" TEXT;
