ALTER TYPE "LedgerType" ADD VALUE IF NOT EXISTS 'ADMIN_REFUND';
ALTER TYPE "LedgerType" ADD VALUE IF NOT EXISTS 'WITHDRAWAL_REQUESTED';
ALTER TYPE "LedgerType" ADD VALUE IF NOT EXISTS 'WITHDRAWAL_APPROVED';
