ALTER TABLE "auctions"
  ADD COLUMN IF NOT EXISTS "starting_price" DECIMAL(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "buy_now_price" DECIMAL(18,2);

ALTER TABLE "Vehicle"
  ADD COLUMN IF NOT EXISTS "description" TEXT,
  ADD COLUMN IF NOT EXISTS "engine" TEXT,
  ADD COLUMN IF NOT EXISTS "drive_type" TEXT,
  ADD COLUMN IF NOT EXISTS "exterior_color" TEXT,
  ADD COLUMN IF NOT EXISTS "interior_color" TEXT,
  ADD COLUMN IF NOT EXISTS "airbags" TEXT,
  ADD COLUMN IF NOT EXISTS "damage" TEXT DEFAULT 'None';
