// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/buyers" | "/admin/companies" | "/admin/events" | "/admin/events/[id]" | "/admin/events/new" | "/admin/vehicles" | "/auctions" | "/auctions/[auctionId]" | "/auctions/live/[auctionId]" | "/buyer/wishlist" | "/dashboard" | "/finance" | "/finance/invoices/[invoiceId]" | "/forgot-password" | "/invoices" | "/invoices/[id]" | "/login" | "/login/buyer" | "/login/seller" | "/my-bids" | "/profile" | "/register" | "/register/buyer" | "/register/seller" | "/seller" | "/seller/auctions" | "/seller/auctions/[auctionId]" | "/seller/dashboard" | "/seller/settings" | "/seller/settings/company" | "/seller/settings/documents" | "/seller/settings/notifications" | "/seller/settings/team" | "/seller/vehicles" | "/seller/vehicles/[vehicleId]" | "/seller/vehicles/new" | "/wallet" | "/watchlist"
type AppRouteHandlerRoutes = "/api/auth/token" | "/api/seller/vehicles/media/[batchId]/[fileName]" | "/api/seller/vehicles/upload-photos" | "/uploads/[...segments]"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/seller" | "/seller/settings"
type RedirectRoutes = never
type RewriteRoutes = "/api/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/buyers": {}
  "/admin/companies": {}
  "/admin/events": {}
  "/admin/events/[id]": { "id": string; }
  "/admin/events/new": {}
  "/admin/vehicles": {}
  "/api/[[...path]]": { "path"?: string[]; }
  "/api/auth/token": {}
  "/api/seller/vehicles/media/[batchId]/[fileName]": { "batchId": string; "fileName": string; }
  "/api/seller/vehicles/upload-photos": {}
  "/auctions": {}
  "/auctions/[auctionId]": { "auctionId": string; }
  "/auctions/live/[auctionId]": { "auctionId": string; }
  "/buyer/wishlist": {}
  "/dashboard": {}
  "/finance": {}
  "/finance/invoices/[invoiceId]": { "invoiceId": string; }
  "/forgot-password": {}
  "/invoices": {}
  "/invoices/[id]": { "id": string; }
  "/login": {}
  "/login/buyer": {}
  "/login/seller": {}
  "/my-bids": {}
  "/profile": {}
  "/register": {}
  "/register/buyer": {}
  "/register/seller": {}
  "/seller": {}
  "/seller/auctions": {}
  "/seller/auctions/[auctionId]": { "auctionId": string; }
  "/seller/dashboard": {}
  "/seller/settings": {}
  "/seller/settings/company": {}
  "/seller/settings/documents": {}
  "/seller/settings/notifications": {}
  "/seller/settings/team": {}
  "/seller/vehicles": {}
  "/seller/vehicles/[vehicleId]": { "vehicleId": string; }
  "/seller/vehicles/new": {}
  "/uploads/[...segments]": { "segments": string[]; }
  "/wallet": {}
  "/watchlist": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/seller": never
  "/seller/settings": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
