var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/auctions/[auctionId]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__c6fefdfc._.js")
R.c("server/chunks/ssr/_a288d704._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/node_modules_next_dist_9764e5f5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5155cd89._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7f68cf2f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__f5a4994d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_auctions_[auctionId]_page_actions_c1f176ca.js")
R.m(45492)
module.exports=R.m(45492).exports
