var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/auctions/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__f3051a07._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/_069b8ad9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__01f5b447._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7f68cf2f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_6607e1c8._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__7e2c0f0f._.js")
R.c("server/chunks/ssr/node_modules_next_99977b66._.js")
R.c("server/chunks/ssr/node_modules_next_dist_981dc6eb._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_auctions_page_actions_949d08e8.js")
R.m(95346)
module.exports=R.m(95346).exports
