// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/admin/buyers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/buyers">> = Specific
  const handler = {} as typeof import("../../../app/admin/buyers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/companies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/companies">> = Specific
  const handler = {} as typeof import("../../../app/admin/companies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/events/[id]/console/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/events/[id]/console">> = Specific
  const handler = {} as typeof import("../../../app/admin/events/[id]/console/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/events/[id]/lots/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/events/[id]/lots">> = Specific
  const handler = {} as typeof import("../../../app/admin/events/[id]/lots/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/events/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/events/[id]">> = Specific
  const handler = {} as typeof import("../../../app/admin/events/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/events/[id]/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/events/[id]/results">> = Specific
  const handler = {} as typeof import("../../../app/admin/events/[id]/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/events/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/events/new">> = Specific
  const handler = {} as typeof import("../../../app/admin/events/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/events">> = Specific
  const handler = {} as typeof import("../../../app/admin/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/vehicles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/vehicles">> = Specific
  const handler = {} as typeof import("../../../app/admin/vehicles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auctions/live/[auctionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auctions/live/[auctionId]">> = Specific
  const handler = {} as typeof import("../../../app/auctions/live/[auctionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auctions/live/event/[eventId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auctions/live/event/[eventId]">> = Specific
  const handler = {} as typeof import("../../../app/auctions/live/event/[eventId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auctions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auctions">> = Specific
  const handler = {} as typeof import("../../../app/auctions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/buyer/wishlist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/buyer/wishlist">> = Specific
  const handler = {} as typeof import("../../../app/buyer/wishlist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/finance/invoices/[invoiceId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/invoices/[invoiceId]">> = Specific
  const handler = {} as typeof import("../../../app/finance/invoices/[invoiceId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance">> = Specific
  const handler = {} as typeof import("../../../app/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../../app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/invoices/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoices/[id]">> = Specific
  const handler = {} as typeof import("../../../app/invoices/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/invoices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoices">> = Specific
  const handler = {} as typeof import("../../../app/invoices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/buyer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login/buyer">> = Specific
  const handler = {} as typeof import("../../../app/login/buyer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/seller/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login/seller">> = Specific
  const handler = {} as typeof import("../../../app/login/seller/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/my-bids/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my-bids">> = Specific
  const handler = {} as typeof import("../../../app/my-bids/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../../app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/register/buyer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register/buyer">> = Specific
  const handler = {} as typeof import("../../../app/register/buyer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../../app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/register/seller/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register/seller">> = Specific
  const handler = {} as typeof import("../../../app/register/seller/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/seller/auctions/[auctionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seller/auctions/[auctionId]">> = Specific
  const handler = {} as typeof import("../../../app/seller/auctions/[auctionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/seller/auctions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seller/auctions">> = Specific
  const handler = {} as typeof import("../../../app/seller/auctions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/seller/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seller/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/seller/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/seller/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seller">> = Specific
  const handler = {} as typeof import("../../../app/seller/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/seller/settings/company/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seller/settings/company">> = Specific
  const handler = {} as typeof import("../../../app/seller/settings/company/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/seller/settings/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seller/settings/documents">> = Specific
  const handler = {} as typeof import("../../../app/seller/settings/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/seller/settings/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seller/settings/notifications">> = Specific
  const handler = {} as typeof import("../../../app/seller/settings/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/seller/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seller/settings">> = Specific
  const handler = {} as typeof import("../../../app/seller/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/seller/settings/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seller/settings/team">> = Specific
  const handler = {} as typeof import("../../../app/seller/settings/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/seller/vehicles/[vehicleId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seller/vehicles/[vehicleId]">> = Specific
  const handler = {} as typeof import("../../../app/seller/vehicles/[vehicleId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/seller/vehicles/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seller/vehicles/new">> = Specific
  const handler = {} as typeof import("../../../app/seller/vehicles/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/seller/vehicles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seller/vehicles">> = Specific
  const handler = {} as typeof import("../../../app/seller/vehicles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/wallet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wallet">> = Specific
  const handler = {} as typeof import("../../../app/wallet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/watchlist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/watchlist">> = Specific
  const handler = {} as typeof import("../../../app/watchlist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/token">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/seller/vehicles/media/[batchId]/[fileName]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/seller/vehicles/media/[batchId]/[fileName]">> = Specific
  const handler = {} as typeof import("../../../app/api/seller/vehicles/media/[batchId]/[fileName]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/seller/vehicles/upload-photos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/seller/vehicles/upload-photos">> = Specific
  const handler = {} as typeof import("../../../app/api/seller/vehicles/upload-photos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/uploads/[...segments]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/uploads/[...segments]">> = Specific
  const handler = {} as typeof import("../../../app/uploads/[...segments]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auctions/live/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/auctions/live">> = Specific
  const handler = {} as typeof import("../../../app/auctions/live/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/seller/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/seller">> = Specific
  const handler = {} as typeof import("../../../app/seller/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/seller/settings/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/seller/settings">> = Specific
  const handler = {} as typeof import("../../../app/seller/settings/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
