var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/invoices/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__206c34f5._.js")
R.c("server/chunks/ssr/_566c6625._.js")
R.c("server/chunks/ssr/_d67bfa67._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5155cd89._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7f68cf2f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__f5a4994d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_invoices_page_actions_949cb4db.js")
R.m(62645)
module.exports=R.m(62645).exports
